

#include <stdio.h>
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "esp_timer.h"

#include "driver/gpio.h"
#include "driver/i2s.h"
//#include "driver/i2s_std.h"
#include "driver/gpio.h"
#include "math.h"


#define CHUNK_SIZE 2048
#define FULL_RANGE 32767
#define BITRATE 48000

size_t bytes_written = CHUNK_SIZE;

size_t bytes_read = 0;

double time_in_ms = 0;

// i2s_chan_handle_t tx_handle;
// i2s_chan_handle_t rx_handle;

int32_t data[CHUNK_SIZE] = {0};




void setup_dac(){
    // /* Setting the configurations, the slot configuration and clock configuration can be generated by the macros
    // * These two helper macros are defined in 'i2s_std.h' which can only be used in STD mode.
    // * They can help to specify the slot and clock configurations for initialization or updating */
    // i2s_chan_config_t chan_tx_cfg = I2S_CHANNEL_DEFAULT_CONFIG(I2S_NUM_AUTO, I2S_ROLE_MASTER);
    // i2s_new_channel(&chan_tx_cfg, &tx_handle, NULL);
    // i2s_std_config_t std_tx_cfg = {
    //     .clk_cfg = I2S_STD_CLK_DEFAULT_CONFIG(BITRATE),
    //     .slot_cfg = I2S_STD_PHILIPS_SLOT_DEFAULT_CONFIG(I2S_DATA_BIT_WIDTH_16BIT, I2S_SLOT_MODE_STEREO),
    //     .gpio_cfg = {
    //         .mclk = GPIO_NUM_0,
    //         .bclk = GPIO_NUM_4,
    //         .ws = GPIO_NUM_5,
    //         .dout = GPIO_NUM_18,
    //         .din = I2S_GPIO_UNUSED,
    //         .invert_flags = {
    //             .mclk_inv = false,
    //             .bclk_inv = false,
    //             .ws_inv = false,
    //         },
    //     },
    // };
    // /* Initialize the channel */
    // i2s_channel_init_std_mode(tx_handle, &std_tx_cfg);

    // /* Before writing data, start the TX channel first */
    // i2s_channel_enable(tx_handle);

    i2s_config_t dacI2SConfig = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_TX),
        .sample_rate = BITRATE,
        .bits_per_sample = I2S_BITS_PER_CHAN_16BIT,
        .channel_format = I2S_CHANNEL_FMT_RIGHT_LEFT,
        .communication_format = I2S_COMM_FORMAT_I2S_MSB,
        .intr_alloc_flags = ESP_INTR_FLAG_LEVEL1,

        .dma_buf_count = 2,
        .dma_buf_len = 1024,
        .use_apll = false,
        .tx_desc_auto_clear = false,
        .fixed_mclk = 0

    };

    i2s_pin_config_t dacI2SPins = {
        .bck_io_num = 4,
        .data_out_num = 18,
        .mck_io_num = 0,
        .ws_io_num = 5,
        .data_in_num = I2S_PIN_NO_CHANGE
    };

    i2s_driver_install(1, &dacI2SConfig, 0, NULL);   //install and start i2s driver
    i2s_set_pin(1, &dacI2SPins);
}


void setup_adc(){

    i2s_config_t adcI2SConfig = {
        .mode = (i2s_mode_t)(I2S_MODE_MASTER | I2S_MODE_RX | I2S_MODE_ADC_BUILT_IN),
        .sample_rate = BITRATE,
        .bits_per_sample = I2S_BITS_PER_SAMPLE_16BIT,
        .channel_format = I2S_CHANNEL_FMT_ONLY_LEFT,
        .communication_format = I2S_COMM_FORMAT_I2S_MSB,
        
        .dma_buf_count = 2,
        .dma_buf_len = 1024,
        .use_apll = false,
        .tx_desc_auto_clear = false,
        .fixed_mclk = 0
        };

    
    // i2s_pin_config_t adcI2SPins = {
    //     .bck_io_num = 4,
    //     .data_out_num = 18,
    //     .mck_io_num = 0,
    //     .ws_io_num = 5,
    //     .data_in_num = I2S_PIN_NO_CHANGE
    // };

    i2s_driver_install(0, &adcI2SConfig, 0, NULL);
    i2s_set_pin(0, NULL);
    i2s_set_adc_mode(0, ADC1_CHANNEL_0);
}

float angle = 0;
void generate_sine(float frequency, float amplitude){
    float offset = 2 * M_PI * frequency / BITRATE;
    float amp = FULL_RANGE * amplitude;

    for(int i = 0; i < CHUNK_SIZE; i+=1){
            data[i] = (int16_t)(amp * sinf(angle));
            angle += offset;
            if (angle >= 2*M_PI){ angle = 0; }
    }
}

void app_main() {

    setup_dac();
    setup_adc();

    while(1){

        //generate_sine(1000, 1);

        i2s_read(0, &data, CHUNK_SIZE, &bytes_read, 100);

        //i2s_channel_write(tx_handle, &data, CHUNK_SIZE, &w_bytes, 1000);
        i2s_write(1, data, CHUNK_SIZE, &bytes_written, 100);

        //vTaskDelay(pdMS_TO_TICKS(20));
    }

    // /* Have to stop the channel before deleting it */
    // i2s_channel_disable(tx_handle);
    // /* If the handle is not needed any more, delete it to release the channel resources */
    // i2s_del_channel(tx_handle);
}